### ISSUE TITLE
Missing font file

### ISSUE THREAD

**Issue by aggsol** [LunaRyuko/LunarViewer#12]
I build the current main branch on Ubuntu with premake-linux.sh.
It build successfully but on startup the follwoign error appears.

```
Host machine is little endian
WARNING: IMAGE: Data is not valid to load texture
WARNING: GLFW: Window icon image must be in R8G8B8A8 pixel format
LunarViewer: imgui/imgui_draw.cpp:2150: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
Aborted (core dumped)
```
What font do I need for running the viewer?

**Comment by LunaRyuko** [comment]
So the way I set this up is that its supposed to run in the same working directory as the "game" folder in the root repository

You could straight up just copy the contents of that folder to where the EXE is built, but I honestly have no idea how to set it up automatically.

**Comment by aggsol** [comment]
Ah thank you; i can copy that myself.
